[package]           
name = "btree"      
version = "0.1.0"   
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
                   
[dev-dependencies]  
quickcheck = "0.6"  
rand = "0.4"
